2020-10-01 13:31:39,108 INFO    MainThread:21740 [wandb_init.py:_log_setup():307] Logging user logs to wandb\run-20201001_133139-lq0nkbcp\logs\debug.log
2020-10-01 13:31:39,108 INFO    MainThread:21740 [wandb_init.py:_log_setup():308] Logging internal logs to wandb\run-20201001_133139-lq0nkbcp\logs\debug-internal.log
2020-10-01 13:31:39,108 INFO    MainThread:21740 [wandb_setup.py:_flush():68] setting env: {}
2020-10-01 13:31:39,108 INFO    MainThread:21740 [wandb_setup.py:_flush():68] setting user settings: {}
2020-10-01 13:31:39,108 INFO    MainThread:21740 [wandb_setup.py:_flush():68] multiprocessing start_methods=spawn
2020-10-01 13:31:39,108 WARNING MainThread:21740 [wandb_setup.py:_flush():68] Ignoring settings passed to wandb.setup() which has already been configured.
2020-10-01 13:31:39,111 INFO    MainThread:21740 [wandb_settings.py:_console():393] Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable proper console logging on Windows. Falling back to wrapping stdout/err.
2020-10-01 13:31:39,252 WARNING MainThread:21740 [wandb_setup.py:__init__():209] Ignoring settings passed to wandb.setup() which has already been configured.
2020-10-01 13:31:42,711 INFO    MainThread:21740 [wandb_run.py:_console_start():1134] atexit reg
2020-10-01 13:31:42,713 INFO    MainThread:21740 [wandb_settings.py:_console():393] Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable proper console logging on Windows. Falling back to wrapping stdout/err.
2020-10-01 13:31:42,713 INFO    MainThread:21740 [wandb_run.py:_redirect():1009] redirect: SettingsConsole.REDIRECT
2020-10-01 13:31:42,713 INFO    MainThread:21740 [wandb_run.py:_redirect():1012] Redirecting console.
2020-10-01 13:31:42,713 ERROR   MainThread:21740 [redirect.py:install():184] Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable console logging on Windows.
2020-10-01 13:31:42,713 ERROR   MainThread:21740 [wandb_run.py:_redirect():1059] Failed to redirect.
Traceback (most recent call last):
  File "C:\Users\marcello.borges\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\sdk\wandb_run.py", line 1052, in _redirect
    out_redir.install()
  File "C:\Users\marcello.borges\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\lib\redirect.py", line 185, in install
    raise Exception(msg)
Exception: Set PYTHONLEGACYWINDOWSSTDIO environment variable to enable console logging on Windows.
2020-10-01 13:31:42,729 INFO    MainThread:21740 [wandb_watch.py:watch():32] Watching
2020-10-01 13:31:42,729 INFO    MainThread:21740 [wandb_watch.py:watch():32] Watching
2020-10-02 10:15:45,934 INFO    MainThread:21740 [wandb_run.py:_atexit_cleanup():1112] got exitcode: 1
2020-10-02 10:15:45,999 INFO    MainThread:21740 [wandb_run.py:_restore():1084] restore
2020-10-02 10:15:46,029 INFO    MainThread:21740 [wandb_run.py:_wait_for_finish():1216] got exit ret: uuid: "65d89475e6264dc09a414df6571486d7"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
      media_count: 2
    }
    pusher_stats {
      uploaded_bytes: 1824
      total_bytes: 1824
    }
  }
}

2020-10-02 10:15:48,036 INFO    MainThread:21740 [wandb_run.py:_wait_for_finish():1216] got exit ret: uuid: "ea94c0a1b03c4ba0a9a18fe208715cec"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 4
      media_count: 2
    }
    pusher_stats {
      uploaded_bytes: 26202
      total_bytes: 26202
    }
  }
}

2020-10-02 10:15:50,045 INFO    MainThread:21740 [wandb_run.py:_wait_for_finish():1216] got exit ret: uuid: "86b4ebe5f11447ef8712ad5263f7ac61"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 4
      media_count: 2
    }
    pusher_stats {
      uploaded_bytes: 26202
      total_bytes: 26202
    }
  }
}

2020-10-02 10:15:51,192 INFO    MainThread:21740 [wandb_run.py:_show_summary():1323] rendering summary
2020-10-02 10:15:51,201 INFO    MainThread:21740 [wandb_run.py:_show_history():1347] rendering history
2020-10-02 10:15:51,204 INFO    MainThread:21740 [wandb_run.py:_show_files():1363] logging synced files
2020-10-02 10:15:51,216 INFO    MainThread:21740 [internal.py:handle_exit():137] Internal process exited
